name 'tohuwabohu-duplicity_mysql'
version '1.0.0'
source 'https://github.com/tohuwabohu/puppet-duplicity_mysql.git'
project_page 'https://github.com/tohuwabohu/puppet-duplicity_mysql'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
summary 'Backup and restore MySQL databases based on duplicity.'
description ''
dependency 'tohuwabohu/duplicity', '>= 1.0.0 < 4.0.0'
dependency 'puppetlabs/stdlib', '4.x'
